# Cargo configuration for foia
# https://doc.rust-lang.org/cargo/reference/config.html

[alias]
foia = "run --release --features postgres,browser --"
serve = "run --release --features postgres -- serve"
scrape = "run --release --features postgres,browser -- scrape"
ocr = "run --release --features postgres -- analyze"
status = "run --release --features postgres -- status"
db = "run --release --features postgres -- db"
